import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'hi' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  en: {
    dashboard: 'Road Safety Dashboard',
    subtitle: 'AI-based Road Safety Management System',
    totalVehicles: 'Total Vehicles',
    activeDrivers: 'Active Drivers',
    safetyAlerts: 'Safety Alerts',
    safetyScore: 'Safety Score',
    hotspots: 'Hotspot Areas',
    activities: "Today's Activities",
    liveMonitoring: 'Live Monitoring',
    emergencyResponse: 'Emergency Response',
    analytics: 'AI Analytics',
    reports: 'Safety Reports',
    settings: 'Settings',
    systemStatus: 'System Status',
    allSystemsOnline: 'All systems online',
    chatSupport: 'Chat Support',
    selectLanguage: 'Select Language',
    continue: 'Continue',
    welcomeTitle: 'Welcome to Thore Network',
    welcomeSubtitle: 'AI Safety Portal',
    liveMonitoringTitle: "Live Monitoring",
    liveMonitoringSubtitle: "Real-time vehicle tracking and safety monitoring",
    vehiclesActive: "active vehicles",
    activeAlerts: "Active Alerts",
    coveredCities: "Covered Cities",
    liveVehicleTracking: "Live Vehicle Tracking",
    currentSpeed: "Current Speed",
    high: "High",
    medium: "Medium",
    low: "Low",
    modelAccuracy: "Model Accuracy",
    responseTime: "Response Time",
    dataProcessing: "Data Processing",
    seconds: "seconds",

    aiAnalytics: "AI Analytics",
    analyticsSubtitle: "Data-driven insights and performance metrics",
    aiModelActive: "AI Model Active",
    totalAnalysis: "Total Analysis",
    aiAccuracy: "AI Accuracy",
    improvementRate: "Improvement Rate",
    riskIncidents: "Risk Incidents",
    monthlyTrendAnalysis: "Monthly Trend Analysis",
    incidents: "Incidents",
    predictions: "Predictions",
    accuracy: "Accuracy",
    aiModelPerformance: "AI Model Performance",
    accidentPrediction: "Accident Prediction",
    trafficPattern: "Traffic Pattern Analysis",
    driverBehavior: "Driver Behavior Analysis",
    weatherImpact: "Weather Impact Model",
    advancedAIInsights: "Advanced AI Insights",
    vehicleOptimization: "Vehicle Optimization",
    routePlanningImprovement: "Route planning improved: +18%",
    driverTraining: "Driver Training",
    safetyScoreImprovement: "Safety Score Improvement: +23%",
    realtimeAlerts: "Real-time Alerts",
    responseTimeDown: "Response Time: -45%",

    safetyReports: "Reports & Analysis",
    reportsSubtitle: "Detailed reports and data export",
    downloadReport: "Download Report",
    filter: "Filter",
    allReports: "Total Reports",
    monthlyReports: "Monthly Reports",
    complianceRate: "Compliance Rate",
    recentReports: "Recent Reports",
    reportType: "Type",
    reportStatusReady: "Ready",
    reportStatusInProgress: "In Progress",
    download: "Download",
    reportCategories: "Report Categories",
    safetyReport: "Safety Reports",
    performanceReport: "Performance Reports",
    complianceReport: "Compliance Reports",
    incidentReport: "Incident Reports",
    createCustomReport: "Create Custom Report",
    reportTypeLabel: "Report Type",
    performanceMetrics: "Performance Metrics",
    driverEvaluation: "Driver Evaluation",
    incidentReportSingular: "Incident Report",
    period: "Period",
    lastWeek: "Last Week",
    lastMonth: "Last Month",
    lastThreeMonths: "Last 3 Months",
    customRange: "Custom Range",
    generateReport: "Generate Report",

    settingsTitle: "Settings",
    systemConfig: "System Configuration and Preferences",
    settingsCategory: "Settings Category",
    accountSettings: "Account Settings",
    notifications: "Notifications",
    security: "Security",
    dataManagement: "Data Management",
    language: "Language",
    mobileApp: "Mobile App",
    accountSettingsHeader: "Account Settings",
    fullName: "Full Name",
    email: "Email",
    phoneNumber: "Phone Number",
    position: "Position",
    company: "Company",
    notificationPreferences: "Notification Preferences",
    safetyAlertDesc: "Instant notifications for critical safety events",
    weeklyReports: "Weekly Reports",
    weeklyReportsDesc: "Performance summary every week",
    systemUpdates: "System Updates",
    systemUpdatesDesc: "Information on new features and improvements",
    aiModelSettings: "AI Model Settings",
    riskSensitivity: "Risk Sensitivity",
    highMoreAlerts: "High (More Alerts)",
    mediumBalanced: "Medium (Balanced)",
    lowFewerAlerts: "Low (Fewer Alerts)",
    updateFrequency: "Update Frequency",
    realTime: "Real Time",
    everyMinute: "Every Minute",
    every5Minutes: "Every 5 Minutes",
    cancel: "Cancel",
    saveChanges: "Save Changes",

    emergencyResponseTitle: "Emergency Response",
    emergencySubtitle: "Rapid response and incident management",
    activeIncidents: "Active Incidents",
    responseTeams: "Response Teams",
    avgResponseTime: "Avg Response Time",
    successRate: "Success Rate",
    minutes: "minutes",
    onStandby: "on standby",
    currentEmergencies: "Current Emergencies",
    severity: "Severity",
    location: "Location",
    timeReported: "Time Reported",
    status: "Status",
    action: "Action",
    viewDetails: "View Details",
    inProgress: "In Progress",
    resolved: "Resolved",
    dispatched: "Dispatched",
    responseProtocols: "Response Protocols",
    medicalEmergency: "Medical Emergency",
    medicalDesc: "Immediate medical response protocol",
    trafficAccident: "Traffic Accident",
    trafficDesc: "Traffic management and clearance",
    vehicleBreakdown: "Vehicle Breakdown",
    breakdownDesc: "Roadside assistance coordination",
    weatherHazard: "Weather Hazard",
    weatherDesc: "Weather-related safety measures",
  },
  hi: {
    dashboard: 'सड़क सुरक्षा डैशबोर्ड',
    subtitle: 'AI-आधारित सड़क सुरक्षा प्रबंधन प्रणाली',
    totalVehicles: 'कुल वाहन',
    activeDrivers: 'सक्रिय चालक',
    safetyAlerts: 'सुरक्षा अलर्ट',
    safetyScore: 'सुरक्षा स्कोर',
    hotspots: 'हॉटस्पॉट क्षेत्र',
    activities: 'आज की गतिविधियां',
    liveMonitoring: 'लाइव निगरानी',
    emergencyResponse: 'आपातकालीन प्रतिक्रिया',
    analytics: 'AI विश्लेषण',
    reports: 'सुरक्षा रिपोर्ट',
    settings: 'सेटिंग्स',
    systemStatus: 'सिस्टम स्थिति',
    allSystemsOnline: 'सभी सिस्टम ऑनलाइन',
    chatSupport: 'चैट सहायता',
    selectLanguage: 'भाषा चुनें',
    continue: 'जारी रखें',
    welcomeTitle: 'Thore Network में आपका स्वागत है',
    welcomeSubtitle: 'AI सुरक्षा पोर्टल',
    liveMonitoringTitle: "लाइव मॉनिटरिंग",
    liveMonitoringSubtitle: "रीयल-टाइम वाहन ट्रैकिंग और सुरक्षा निगरानी",
    vehiclesActive: "सक्रिय वाहन",
    activeAlerts: "सक्रिय अलर्ट",
    coveredCities: "को कवर किए गए शहर",
    liveVehicleTracking: "लाइव वाहन ट्रैकिंग",
    currentSpeed: "वर्तमान गति",
    high: "उच्च",
    medium: "मध्यम",
    low: "निम्न",
    modelAccuracy: "मॉडल सटीकता",
    responseTime: "प्रतिक्रिया समय",
    dataProcessing: "डेटा प्रोसेसिंग",
    seconds: "सेकंड",

    aiAnalytics: "एआई एनालिटिक्स",
    analyticsSubtitle: "डेटा-आधारित अंतर्दृष्टि और प्रदर्शन मीट्रिक्स",
    aiModelActive: "एआई मॉडल सक्रिय",
    totalAnalysis: "कुल विश्लेषण",
    aiAccuracy: "एआई सटीकता",
    improvementRate: "सुधार दर",
    riskIncidents: "जोखिम घटनाएँ",
    monthlyTrendAnalysis: "मासिक ट्रेंड विश्लेषण",
    incidents: "घटनाएँ",
    predictions: "भविष्यवाणियाँ",
    accuracy: "सटीकता",
    aiModelPerformance: "एआई मॉडल प्रदर्शन",
    accidentPrediction: "दुर्घटना पूर्वानुमान",
    trafficPattern: "ट्रैफिक पैटर्न विश्लेषण",
    driverBehavior: "चालक व्यवहार विश्लेषण",
    weatherImpact: "मौसम प्रभाव मॉडल",
    advancedAIInsights: "एडवांस्ड एआई अंतर्दृष्टि",
    vehicleOptimization: "वाहन अनुकूलन",
    routePlanningImprovement: "रूट प्लानिंग सुधार: +१८%",
    driverTraining: "चालक प्रशिक्षण",
    safetyScoreImprovement: "सुरक्षा स्कोर सुधार: +२३%",
    realtimeAlerts: "रीयल-टाइम अलर्ट्स",
    responseTimeDown: "प्रतिक्रिया समय: -४५%",

    safetyReports: "रिपोर्ट्स और विश्लेषण",
    reportsSubtitle: "विस्तृत रिपोर्ट्स और डेटा निर्यात",
    downloadReport: "रिपोर्ट डाउनलोड करें",
    filter: "फिल्टर",
    allReports: "कुल रिपोर्ट",
    monthlyReports: "मासिक रिपोर्ट",
    complianceRate: "अनुपालन दर",
    recentReports: "हालिया रिपोर्ट्स",
    reportType: "प्रकार",
    reportStatusReady: "तैयार",
    reportStatusInProgress: "प्रक्रिया में",
    download: "डाउनलोड",
    reportCategories: "रिपोर्ट श्रेणियाँ",
    safetyReport: "सुरक्षा रिपोर्ट्स",
    performanceReport: "प्रदर्शन रिपोर्ट्स",
    complianceReport: "अनुपालन रिपोर्ट्स",
    incidentReport: "घटना रिपोर्ट्स",
    createCustomReport: "कस्टम रिपोर्ट बनाएँ",
    reportTypeLabel: "रिपोर्ट प्रकार",
    performanceMetrics: "प्रदर्शन मीट्रिक्स",
    driverEvaluation: "चालक मूल्यांकन",
    incidentReportSingular: "घटना रिपोर्ट",
    period: "अवधि",
    lastWeek: "पिछला सप्ताह",
    lastMonth: "पिछला महीना",
    lastThreeMonths: "पिछले 3 महीने",
    customRange: "कस्टम रेंज",
    generateReport: "रिपोर्ट बनाएं",

    settingsTitle: "सेटिंग्स",
    systemConfig: "सिस्टम कॉन्फ़िगरेशन और प्राथमिकताएँ",
    settingsCategory: "सेटिंग्स श्रेणी",
    accountSettings: "खाता सेटिंग्स",
    notifications: "सूचनाएं",
    security: "सुरक्षा",
    dataManagement: "डेटा प्रबंधन",
    language: "भाषा",
    mobileApp: "मोबाइल ऐप",
    accountSettingsHeader: "खाता सेटिंग्स",
    fullName: "पूरा नाम",
    email: "ईमेल",
    phoneNumber: "फ़ोन नंबर",
    position: "पद",
    company: "कंपनी",
    notificationPreferences: "सूचना प्राथमिकताएँ",
    safetyAlertDesc: "गंभीर सुरक्षा घटनाओं के लिए तुरंत सूचनाएँ",
    weeklyReports: "साप्ताहिक रिपोर्ट्स",
    weeklyReportsDesc: "प्रत्येक सप्ताह प्रदर्शन सारांश",
    systemUpdates: "सिस्टम अपडेट्स",
    systemUpdatesDesc: "नई सुविधाओं और सुधारों की जानकारी",
    aiModelSettings: "एआई मॉडल सेटिंग्स",
    riskSensitivity: "जोखिम संवेदनशीलता",
    highMoreAlerts: "उच्च (अधिक अलर्ट)",
    mediumBalanced: "मध्यम (संतुलित)",
    lowFewerAlerts: "निम्न (कम अलर्ट)",
    updateFrequency: "अपडेट आवृत्ति",
    realTime: "रीयल-टाइम",
    everyMinute: "हर मिनट",
    every5Minutes: "हर 5 मिनट",
    cancel: "रद्द करें",
    saveChanges: "परिवर्तन सहेजें",

    emergencyResponseTitle: "आपातकालीन प्रतिक्रिया",
    emergencySubtitle: "त्वरित प्रतिक्रिया और घटना प्रबंधन",
    activeIncidents: "सक्रिय घटनाएं",
    responseTeams: "प्रतिक्रिया टीमें",
    avgResponseTime: "औसत प्रतिक्रिया समय",
    successRate: "सफलता दर",
    minutes: "मिनट",
    onStandby: "स्टैंडबाई पर",
    currentEmergencies: "वर्तमान आपातकाल",
    severity: "गंभीरता",
    location: "स्थान",
    timeReported: "रिपोर्ट का समय",
    status: "स्थिति",
    action: "कार्य",
    viewDetails: "विवरण देखें",
    inProgress: "प्रक्रिया में",
    resolved: "हल हो गया",
    dispatched: "भेजा गया",
    responseProtocols: "प्रतिक्रिया प्रोटोकॉल",
    medicalEmergency: "चिकित्सा आपातकाल",
    medicalDesc: "तत्काल चिकित्सा प्रतिक्रिया प्रोटोकॉल",
    trafficAccident: "यातायात दुर्घटना",
    trafficDesc: "यातायात प्रबंधन और निकासी",
    vehicleBreakdown: "वाहन खराबी",
    breakdownDesc: "रियल साइड सहायता समन्वय",
    weatherHazard: "मौसम खतरा",
    weatherDesc: "मौसम संबंधी सुरक्षा उपाय",
  }
};

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('en');

  const t = (key: string): string => {
    return translations[language][key as keyof typeof translations['en']] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};
